### ISSUE TITLE
Crash with SkinShuffle

### ISSUE THREAD

**Issue by itslilscorp** [usevital/vital#4]
**Describe the bug**
On a clean install, the SkinShuffle mod appears to be non-functional. If I try to interact with the mod, the game crashes.

**To Reproduce**
1. Open game
2. Click on Skin Presets
3. Click Select Preset
4. See game crash

**Expected behavior**
SkinShuffle should allow me to change my skin and not immediately crash :]

**Screenshots**
![image](https://github.com/user-attachments/assets/84a5e2b5-e707-4834-b2b6-6ec434e585b2)

**Device info (please complete the following information):**
 - OS: Windows 11
 - Minecraft version: 1.20.1
 - Launcher: Prism

**Additional context**
This issue doesn't arise when using SkinShuffle on its own, so I believe it may be an incompatibility with another mod in this pack.

<details log>
<summary>Here's a log of the crash.</summary>
<pre>
[16:16:39] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: mouseClicked event handler
	at net.minecraft.class_437.method_25412(class_437.java:414) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:169) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:102) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:169) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar:?]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar:?]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474) ~[lwjgl-glfw-3.3.1.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:237) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1244) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) ~[fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.16.5.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[NewLaunch.jar:?]
Caused by: java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 1
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
	at java.util.Objects.checkIndex(Objects.java:359) ~[?:?]
	at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
	at com.mineblock11.skinshuffle.client.gui.CarouselScreen.lambda$init$6(CarouselScreen.java:142) ~[SkinShuffle-2.2.2+1.20.1.jar:?]
	at dev.lambdaurora.spruceui.widget.SpruceButtonWidget.onPress(SpruceButtonWidget.java:32) ~[spruceui-5.0.0+1.20-a7e7164e506142b1.jar:?]
	at dev.lambdaurora.spruceui.widget.AbstractSprucePressableButtonWidget.onClick(AbstractSprucePressableButtonWidget.java:32) ~[spruceui-5.0.0+1.20-a7e7164e506142b1.jar:?]
	at dev.lambdaurora.spruceui.widget.AbstractSpruceButtonWidget.onMouseClick(AbstractSpruceButtonWidget.java:98) ~[spruceui-5.0.0+1.20-a7e7164e506142b1.jar:?]
	at dev.lambdaurora.spruceui.widget.AbstractSpruceWidget.method_25402(AbstractSpruceWidget.java:136) ~[spruceui-5.0.0+1.20-a7e7164e506142b1.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:38) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:409) ~[client-intermediary.jar:?]
	... 17 more
[16:16:40] [Render thread/INFO]: [FastQuit] Exiting FastQuit.
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2024-09-29 16:16:40
Description: mouseClicked event handler

java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 1
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at com.mineblock11.skinshuffle.client.gui.CarouselScreen.lambda$init$6(CarouselScreen.java:142)
	at dev.lambdaurora.spruceui.widget.SpruceButtonWidget.onPress(SpruceButtonWidget.java:32)
	at dev.lambdaurora.spruceui.widget.AbstractSprucePressableButtonWidget.onClick(AbstractSprucePressableButtonWidget.java:32)
	at dev.lambdaurora.spruceui.widget.AbstractSpruceButtonWidget.onMouseClick(AbstractSpruceButtonWidget.java:98)
	at dev.lambdaurora.spruceui.widget.AbstractSpruceWidget.method_25402(AbstractSpruceWidget.java:136)
	at net.minecraft.class_4069.method_25402(class_4069.java:38)
	at net.minecraft.class_312.method_1611(class_312.java:98)
	at net.minecraft.class_437.method_25412(class_437.java:409)
	at net.minecraft.class_312.method_1601(class_312.java:98)
	at net.minecraft.class_312.method_22686(class_312.java:169)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:169)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:237)
	at net.minecraft.class_310.method_1523(class_310.java:1244)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at com.mineblock11.skinshuffle.client.gui.CarouselScreen.lambda$init$6(CarouselScreen.java:142)
	at dev.lambdaurora.spruceui.widget.SpruceButtonWidget.onPress(SpruceButtonWidget.java:32)
	at dev.lambdaurora.spruceui.widget.AbstractSprucePressableButtonWidget.onClick(AbstractSprucePressableButtonWidget.java:32)
	at dev.lambdaurora.spruceui.widget.AbstractSpruceButtonWidget.onMouseClick(AbstractSpruceButtonWidget.java:98)
	at dev.lambdaurora.spruceui.widget.AbstractSpruceWidget.method_25402(AbstractSpruceWidget.java:136)
	at net.minecraft.class_4069.method_25402(class_4069.java:38)
	at net.minecraft.class_312.method_1611(class_312.java:98)
	at net.minecraft.class_437.method_25412(class_437.java:409)
	at net.minecraft.class_312.method_1601(class_312.java:98)
	at net.minecraft.class_312.method_22686(class_312.java:169)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:169)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)

-- Affected screen --
Details:
	Screen name: com.mineblock11.skinshuffle.client.gui.LargeCarouselScreen
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:409)
	at net.minecraft.class_312.method_1601(class_312.java:98)
	at net.minecraft.class_312.method_22686(class_312.java:169)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:169)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:237)
	at net.minecraft.class_310.method_1523(class_310.java:1244)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, file/Chat Reporting Helper.zip
Stacktrace:
	at net.minecraft.class_6360.method_36565(class_6360.java:49)
	at net.minecraft.class_310.method_1587(class_310.java:2413)
	at net.minecraft.class_310.method_1514(class_310.java:821)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.6, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 583181968 bytes (556 MiB) / 1233125376 bytes (1176 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-10700KF CPU @ 3.80GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 5
	Microarchitecture: unknown
	Frequency (GHz): 3.79
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: Virtual Desktop Monitor
	Graphics card #0 vendor: Virtual Desktop, Inc.
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: DriverVersion=15.39.56.845
	Graphics card #1 name: USB Mobile Monitor Virtual Display
	Graphics card #1 vendor: Amyuni
	Graphics card #1 VRAM (MB): 0.00
	Graphics card #1 deviceId: unknown
	Graphics card #1 versionInfo: DriverVersion=2.0.0.1
	Graphics card #2 name: USB Mobile Monitor Virtual Display
	Graphics card #2 vendor: Amyuni
	Graphics card #2 VRAM (MB): 0.00
	Graphics card #2 deviceId: unknown
	Graphics card #2 versionInfo: DriverVersion=2.0.0.1
	Graphics card #3 name: USB Mobile Monitor Virtual Display
	Graphics card #3 vendor: Amyuni
	Graphics card #3 VRAM (MB): 0.00
	Graphics card #3 deviceId: unknown
	Graphics card #3 versionInfo: DriverVersion=2.0.0.1
	Graphics card #4 name: USB Mobile Monitor Virtual Display
	Graphics card #4 vendor: Amyuni
	Graphics card #4 VRAM (MB): 0.00
	Graphics card #4 deviceId: unknown
	Graphics card #4 versionInfo: DriverVersion=2.0.0.1
	Graphics card #5 name: USB Mobile Monitor Virtual Display
	Graphics card #5 vendor: Amyuni
	Graphics card #5 VRAM (MB): 0.00
	Graphics card #5 deviceId: unknown
	Graphics card #5 versionInfo: DriverVersion=2.0.0.1
	Graphics card #6 name: USB Mobile Monitor Virtual Display
	Graphics card #6 vendor: Amyuni
	Graphics card #6 VRAM (MB): 0.00
	Graphics card #6 deviceId: unknown
	Graphics card #6 versionInfo: DriverVersion=2.0.0.1
	Graphics card #7 name: USB Mobile Monitor Virtual Display
	Graphics card #7 vendor: Amyuni
	Graphics card #7 VRAM (MB): 0.00
	Graphics card #7 deviceId: unknown
	Graphics card #7 versionInfo: DriverVersion=2.0.0.1
	Graphics card #8 name: USB Mobile Monitor Virtual Display
	Graphics card #8 vendor: Amyuni
	Graphics card #8 VRAM (MB): 0.00
	Graphics card #8 deviceId: unknown
	Graphics card #8 versionInfo: DriverVersion=2.0.0.1
	Graphics card #9 name: NVIDIA GeForce RTX 3080
	Graphics card #9 vendor: NVIDIA (0x10de)
	Graphics card #9 VRAM (MB): 4095.00
	Graphics card #9 deviceId: 0x2206
	Graphics card #9 versionInfo: DriverVersion=32.0.15.6081
	Graphics card #10 name: SuperDisplay Virtual Adapter
	Graphics card #10 vendor: Software by KeloCube
	Graphics card #10 VRAM (MB): 0.00
	Graphics card #10 deviceId: unknown
	Graphics card #10 versionInfo: DriverVersion=3.47.17.59
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 65337.87
	Virtual memory used (MB): 32498.23
	Swap memory total (MB): 32768.00
	Swap memory used (MB): 298.49
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx4096m
	Fabric Mods: 
		animatica: Animatica 0.6.1+1.20.4
		authme: Auth Me 7.0.2+1.20
		bettergrass: BetterGrassify 1.1.1+fabric.1.20.1
		calcmod: CalcMod fabric-1.20-1.3.0
			clientarguments: clientarguments 1.5.1
			org_mariuszgromada_math_mathparser_org-mxparser: MathParser.org-mXparser 5.0.6
		citresewn: CIT Resewn 1.1.5+1.20.1
			citresewn-defaults: CIT Resewn: Defaults 1.1.5+1.20.1
		cloth-config: Cloth Config v11 11.1.118
			cloth-basic-math: cloth-basic-math 0.6.1
		continuity: Continuity 3.0.0-beta.5+1.20.1
		cosmetica: Cosmetica 1.2.9
			com_github_cosmetica-cc_cosmeticadotjava: CosmeticaDotJava 1.11.2
			sulphate: Sulfate 1.1.1
		craftpresence: CraftPresence 2.5.0
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.10+1802ada577
		cubes-without-borders: Cubes Without Borders 2.1.1+1.20
		cull-less-leaves: Cull Less Leaves 1.3.0
		deftulib: DeftuLib 1.8.2
			com_github_ben-manes_caffeine_caffeine: caffeine 3.1.3
			com_squareup_okhttp3_okhttp: okhttp 4.9.3
			com_squareup_okio_okio: okio 3.0.0
			com_squareup_okio_okio-jvm: okio-jvm 3.0.0
			dev_deftu_enhancedeventbus: enhancedeventbus 2.0.0
			elementa: Elementa 649
			universalcraft: UniversalCraft 342
			vigilance: Vigilance 297
		dynamic_fps: Dynamic FPS 3.7.1
			net_lostluma_battery: battery 1.1.0
		ears: Ears 1.4.6
		enhancedblockentities: Enhanced Block Entities 0.9+1.20
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.7
			spruceui: SpruceUI 5.0.0+1.20
		entity_model_features: Entity Model Features 2.2.6
		entity_sound_features: Entity Sound Features 0.4
		entity_texture_features: Entity Texture Features 6.2.4
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		entityculling: EntityCulling 1.7.0
		fabric-api: Fabric API 0.92.2+1.20.1
			fabric-api-base: Fabric API Base 0.4.31+1802ada577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.36+1802ada577
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.13+1802ada577
			fabric-block-api-v1: Fabric Block API (v1) 1.0.11+1802ada577
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.1+1802ada577
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.41+1802ada577
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.2+1802ada577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.34+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.13+1802ada577
			fabric-commands-v0: Fabric Commands (v0) 0.2.51+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.64+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.11+1802ada577
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.5+1802ada577
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.19+1802ada577
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.0.0+de0fd6d177
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.4+1802ada577
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.54+1802ada577
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.0+1c78457f77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.2+1802ada577
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.63+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.40+1802ada577
			fabric-item-api-v1: Fabric Item API (v1) 2.1.28+1802ada577
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.12+1802ada577
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.37+1802ada577
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.35+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.22+1802ada577
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.1+1802ada577
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.45+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.9+1802ada577
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.50+1802ada577
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.3+1802ada577
			fabric-models-v0: Fabric Models (v0) 0.4.2+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.11+1802ada577
			fabric-networking-v0: Fabric Networking (v0) 0.3.51+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.3+1802ada577
			fabric-particles-v1: Fabric Particles (v1) 1.1.2+1802ada577
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.21+1802ada577
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.3+1802ada577
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.1+1802ada577
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.2+85287f9f77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.46+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.37+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.28+1802ada577
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.49+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.8+1802ada577
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.8+1802ada577
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.8+1802ada577
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.30+1802ada577
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.13+1802ada577
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.5+8dd72ea377
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.1+1802ada577
		fabric-language-kotlin: Fabric Language Kotlin 1.12.1+kotlin.2.0.20
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.20
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.20
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.20
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.20
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.25.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.1
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.1
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.1
			org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm: kotlinx-io-bytestring-jvm 0.5.3
			org_jetbrains_kotlinx_kotlinx-io-core-jvm: kotlinx-io-core-jvm 0.5.3
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.7.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.7.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.7.1
		fabricloader: Fabric Loader 0.16.5
			mixinextras: MixinExtras 0.4.1
		fabricskyboxes: FabricSkyBoxes 0.7.3+mc1.20.1
		fancymenu: FancyMenu 3.2.3
			com_github_keksuccino_japng: japng 0.5.3
			com_github_rtyley_animated-gif-lib-for-java: animated-gif-lib-for-java animated-gif-lib-1.7
		fastquit: FastQuit 3.0.0+1.20+
		ferritecore: FerriteCore 6.0.1
		fix-keyboard-on-linux: Fix Keyboard on Linux 1.0.1
		fsb-interop: FabricSkyBoxes Interop 1.3.6+mc1.20.1-build.50
		immediatelyfast: ImmediatelyFast 1.2.21+1.20.4
			net_lenni0451_reflect: Reflect 1.3.4
		indium: Indium 1.0.34+mc1.20.1
		iris: Iris 1.7.2+mc1.20.1
			io_github_douira_glsl-transformer: glsl-transformer 2.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.13.1
		isxander-main-menu-credits: Main Menu Credits 1.1.2
		java: Java HotSpot(TM) 64-Bit Server VM 17
		konkrete: Konkrete 1.8.1
		lambdynlights: LambDynamicLights 2.3.2+1.20.1
			pride: Pride Lib 1.2.0+1.19.4
		languagereload: Language Reload 1.6.1+1.20.1
		lithium: Lithium 0.11.2
		macos_input_fixes: MacOS Input Fixes 1.7
		melody: Melody 1.0.3
		minecraft: Minecraft 1.20.1
		modelfix: Model Gap Fix 1.15
		modernfix: ModernFix 5.19.4+mc1.20.1
		modmenu: Mod Menu 7.2.2
		noisium: Noisium 2.3.0+mc1.20-1.20.1
		optigui: OptiGUI 2.1.7
			optiglue: OptiGlue 2.1.7-mc.1.19.3
			org_apache_commons_commons-text: commons-text 1.10.0
			org_ini4j_ini4j: ini4j 0.5.4
		polytone: Polytone 1.20-2.3.2
			net_objecthunter_exp4j: exp4j 0.4.8
		puzzle: Puzzle 1.5.2+1.20
			midnightlib: MidnightLib 1.4.1
			puzzle-base: Puzzle Base 1.5.2+1.20
			puzzle-gui: Puzzle GUI 1.5.2+1.20
			puzzle-models: Puzzle Models 1.5.2+1.20
			puzzle-splashscreen: Puzzle Splash Screen 1.5.2+1.20
		reeses-sodium-options: Reese's Sodium Options 1.7.2+mc1.20.1-build.101
		resolutioncontrol: ResolutionControl+ 1.20-3.0.0
		screencapper: Screencapper 1.4.5
			ca_weblite_java-objc-bridge: java-objc-bridge 1.2
		screenshot_viewer: Screenshot Viewer 1.3.1-fabric-mc1.20
			catconfig-mc: Cat Config MC 0.2.1
				io_github_lgatodu47_catconfig: catconfig 0.3.0
		skinshuffle: SkinShuffle 2.2.2+1.20.1
			com_konghq_unirest-java_standalone: unirest-java 3.11.9
			commons-validator_commons-validator: commons-validator 1.7
			org_jsoup_jsoup: jsoup 1.16.1
			org_mineskin_java-client: java-client 1.2.4-SNAPSHOT
		sodium: Sodium 0.5.11+mc1.20.1
		sodium-extra: Sodium Extra 0.5.4+mc1.20.1-build.115
			caffeineconfig: CaffeineConfig 1.3.0+1.17
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
		threadtweak: ThreadTweak 1.20.2-0.1.1
		unilib: UniLib 1.0.2
		world-host: World Host 0.4.14+1.20.1-fabric
			org_quiltmc_parsers_json: json 0.3.0
			org_semver4j_semver4j: semver4j 5.3.0
		yet_another_config_lib_v3: YetAnotherConfigLib 3.5.0+1.20.1-fabric
			com_twelvemonkeys_common_common-image: common-image 3.10.0
			com_twelvemonkeys_common_common-io: common-io 3.10.0
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
			org_quiltmc_parsers_gson: gson 0.2.1
		yosbr: YOSBR 0.1.2
		zoomify: Zoomify 2.14.0+1.20.1
			com_akuleshov7_ktoml-core-jvm: ktoml-core-jvm 0.5.1
	Loaded Shaderpack: (off)
	Launched Version: 1.20.1
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 3080/PCIe/SSE2 GL version 3.2.0 NVIDIA 560.81, NVIDIA Corporation
	Window size: 854x480
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, fabric, file/Chat Reporting Helper.zip
	Current Language: en_us
	CPU: 16x Intel(R) Core(TM) i7-10700KF CPU @ 3.80GHz
#@!@# Game crashed! Crash report saved to: #@!@# D:\MultiMC\instances\Vital Modpack\.minecraft\crash-reports\crash-2024-09-29_16.16.40-client.txt
[16:16:40] [CraftPresence/INFO]: Shutting down CraftPresence...
Process exited with code -1.
</pre>
</details>

**Comment by itslilscorp** [comment]
After playing around with it a little bit, it seems like disabling fancymenu fixes the problem. Not sure if it's a mod compatibility issue or if it's caused by something in the custom fancymenu config for the modpack.

**Comment by KTrain5169** [comment]
Have you tried with only FancyMenu and SkinShuffle?

**Comment by KTrain5169** [comment]
Update: Just tested with Additive 1.30.0 for 1.21.1 Fabric + SkinShuffle + FancyMenu (so I can get default configs), doesn't crash.

**Comment by itslilscorp** [comment]
Yes I tested with just those two, and with the default config for both mods. For me, once title screen customization is enabled in fancymenu, even if nothing is actually changed, skinshuffle refuses to function.

**Comment by KTrain5169** [comment]
Interesting, this could perhaps be an issue to report to SkinShuffle/FancyMenu? We'll probably need to do a little more testing.

I'll get around to testing it later today local time. Thanks for reporting this issue!

**Comment by itslilscorp** [comment]
I reported it to SkinShuffle in their Discord after reporting it here since I assumed the error was on their side (their mod is the one disabling itself after all). I've yet to get any response, but the dev has said in other support tickets that they are busy w school, so I'm unsure if/when they'll get around to looking at it. 

If you need anything from me, I'm in the Vital Discord as well and I'll likely be more reachable there if you @ me.

**Comment by itslilscorp** [comment]
I saw that recommended in different places as well. Doesn't seem to fix the issue for me. This screenshot is from after deleting SkinShuffle's config folder. It seems like an issue starting with SkinShuffle 2.1.0. Going back to 2.0.4 fixes it for me.
![image](https://github.com/user-attachments/assets/9e509554-eb9a-4854-b797-8d4ade7f99c8)

**Comment by itslilscorp** [comment]
Just so everyone is clear and up to date in the thread with the issue I'm experiencing, I created a brand new instance with only SkinShuffle 2.2.2, FancyMenu 3.2.3, and all dependencies as provided in Vital 1.2.0 for 1.20.1.
![image](https://github.com/user-attachments/assets/94dbba24-b42c-4506-9a2d-039bcc92354b)

On the first launch, everything loads as expected.
![image](https://github.com/user-attachments/assets/c2c6a509-1bd1-4161-bc8e-9dd55ff2583b)

If I go and enable "Current Screen Customization" for the title screen, things continue to work as expected.
![image](https://github.com/user-attachments/assets/ac2dd20d-893c-40db-b477-b8dda503e5c0)

However, once I restart the game, SkinShuffle no longer shows the player on the title screen and the Skin Presets menu completely breaks.
![image](https://github.com/user-attachments/assets/e261f0a2-b01f-4dff-b2b9-9252b2bed8cd)
![image](https://github.com/user-attachments/assets/e47d591b-64bf-4416-8982-ca0e81bc1233)

Deleting the SkinShuffle config folder and rebooting the game doesn't change anything. That said, if I delete the SkinShuffle config folder and revert SkinShuffle back to 2.0.4, it appears to work as intended. Any newer version has the aforementioned issue.
![image](https://github.com/user-attachments/assets/559eeb8a-81f4-4f17-a47e-e91345e69ed4)

**Comment by KTrain5169** [comment]
> I reported it to SkinShuffle in their Discord after reporting it here since I assumed the error was on their side (their mod is the one disabling itself after all). I've yet to get any response, but the dev has said in other support tickets that they are busy w school, so I'm unsure if/when they'll get around to looking at it.

@itslilscorp might actually be worth reporting to FancyMenu as well if you can

**Comment by omo50** [comment]
This has been fixed in the upcoming next version, thanks for reporting!

**Comment by worldwidepixel** [comment]
Should this issue be closed if it was fixed in October?
